### ISSUE TITLE
[CRASH] InvocationTargetException: null and java.lang.NoSuchFieldError: PALETTES_CREATIVE_TAB

### ISSUE THREAD

**Issue by JukoiDev** [rbasamoyai/CreateBigCannons#1]
Hi, I am experiencing some crashes when trying to load the mod. The Minecraft displays **InvocationTargetException: null** crash error. But the crashlogs seems to point out the issue:

https://pastebin.com/hRL4drAe

Mod List: 
1. **forge-1.18.2-40.1.55-universal.jar**  
2. **flywheel-forge-1.18-0.6.4.jar**
3. **create-mc1.18.2_v0.5.0c.jar**           
4. (and of course create big cannons)

Thanks in advance.

**Comment by rbasamoyai** [comment]
Should be fixed as of https://github.com/rbasamoyai/CreateBigCannons/commit/8799ad3325dd475f752bac97c10773736ad91b04.

**Comment by JukoiDev** [comment]
Thank you so much!

**Comment by JukoiDev** [comment]
Hey, I am reopening this, because i dont think that commit fixes this crash. Could it be problem with my build? I am using Java-17 and gradle build to build the project.

**Comment by JukoiDev** [comment]
I've fixed it by change the metal sound.

**Comment by rbasamoyai** [comment]
I'd like to note that from what it seems there's an issue within Create regarding the Palettes tab, which seems to have deleted it. Nothing it seems on my end, I tried loading 0.5c with and without Big Cannons and it seems like the tab is still absent. I was mostly intending for the mod to get a prime spot next to Create (grouping addons together), but from what it seems the absent tab was an issue.

The issue will be closed for now as resolved, and if there are any issues you find during independent builds (although I would not advise to continue doing so), please open it in a separate issue. Thank you for the comment as well!
